dataset: 
    folderPath: CS271_final_data
    malwareSample: e  # b,c,d,e,f
params:
    archParams: 
        imgSize: [224,224,3]
        layers: [2,3,4,5]
        fclayers: [128, 256, 512]
        kernelSize: 3
    trainingParams:
        lr: [1e-3, 1e-4]
        optimizer: Adam
        dropoutRate: [0.3,0.4,0.5]
        batchSize: 32

